
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'SUBJECT UNKNOWN VERB_Contpast VERB_Spast VERB_Spresent VERB_pastToBe WORDtexto : frase_presenteSimple textotexto : frase_pasadoSimple textotexto : frase_pasadoContinuo textotexto : emptyfrase_presenteSimple : SUBJECT VERB_Spresent predicatedfrase_pasadoContinuo : SUBJECT VERB_pastToBe VERB_Contpast predicatedfrase_pasadoSimple : SUBJECT VERB_Spast predicatedpredicated : WORDOPT predicatedpredicated : WORDOPTWORDOPT : WORDWORDOPT : emptyempty :'
    
_lr_action_items = {'SUBJECT':([0,2,3,4,10,11,13,14,15,16,17,18,19,20,],[6,6,6,6,-12,-12,-5,-9,-10,-11,-7,-12,-8,-6,]),'$end':([0,1,2,3,4,5,7,8,9,10,11,13,14,15,16,17,18,19,20,],[-12,0,-12,-12,-12,-4,-1,-2,-3,-12,-12,-5,-9,-10,-11,-7,-12,-8,-6,]),'VERB_Spresent':([6,],[10,]),'VERB_Spast':([6,],[11,]),'VERB_pastToBe':([6,],[12,]),'WORD':([10,11,14,15,16,18,],[15,15,15,-10,-11,15,]),'VERB_Contpast':([12,],[18,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'texto':([0,2,3,4,],[1,7,8,9,]),'frase_presenteSimple':([0,2,3,4,],[2,2,2,2,]),'frase_pasadoSimple':([0,2,3,4,],[3,3,3,3,]),'frase_pasadoContinuo':([0,2,3,4,],[4,4,4,4,]),'empty':([0,2,3,4,10,11,14,18,],[5,5,5,5,16,16,16,16,]),'predicated':([10,11,14,18,],[13,17,19,20,]),'WORDOPT':([10,11,14,18,],[14,14,14,14,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> texto","S'",1,None,None,None),
  ('texto -> frase_presenteSimple texto','texto',2,'p_textoSP','TraductorTypes.py',74),
  ('texto -> frase_pasadoSimple texto','texto',2,'p_textoSPast','TraductorTypes.py',78),
  ('texto -> frase_pasadoContinuo texto','texto',2,'p_textoPastCont','TraductorTypes.py',82),
  ('texto -> empty','texto',1,'p_textoOPT','TraductorTypes.py',86),
  ('frase_presenteSimple -> SUBJECT VERB_Spresent predicated','frase_presenteSimple',3,'p_Frase_SP','TraductorTypes.py',90),
  ('frase_pasadoContinuo -> SUBJECT VERB_pastToBe VERB_Contpast predicated','frase_pasadoContinuo',4,'p_Frase_PastCont','TraductorTypes.py',94),
  ('frase_pasadoSimple -> SUBJECT VERB_Spast predicated','frase_pasadoSimple',3,'p_Frase_SPast','TraductorTypes.py',98),
  ('predicated -> WORDOPT predicated','predicated',2,'p_Predicado','TraductorTypes.py',102),
  ('predicated -> WORDOPT','predicated',1,'p_Predicado_Word','TraductorTypes.py',106),
  ('WORDOPT -> WORD','WORDOPT',1,'p_Word_Opt1','TraductorTypes.py',110),
  ('WORDOPT -> empty','WORDOPT',1,'p_Word_OptE','TraductorTypes.py',114),
  ('empty -> <empty>','empty',0,'p_empty','TraductorTypes.py',118),
]
